# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06f57381f1428f65d736fd57d3afc9bae461c8ddfefa3b9f286f43122e160028f6bc981e3755380d7faf2e121260f6de3936ee6d37e7bf7788624b991b047b55

test:
  secret_key_base: f23adcf7d2df5692a4b53197bc493408e27edda602de60fb06ba43950dcf9242340ae12b18ba07a90a6cce3a494c4a55a1b90d1c20e2ccdbf4ae4ba980042f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
